Remove unsupported -foffload-fp32-prec-div flag from quantVLLM-sycl
This flag is Intel DPC++ specific and not supported by other SYCL
compilers (e.g. AdaptiveCpp, open-source clang), causing:

  error: unknown argument: '-foffload-fp32-prec-div'