Add missing <cmath> include to is-sycl and rushlarsen-sycl
SYCL compilers do not implicitly provide C math functions (ceil, sqrt)
through runtime headers like CUDA/HIP do, causing:

  error: use of undeclared identifier 'ceil'   (is-sycl)
  error: use of undeclared identifier 'sqrt'   (rushlarsen-sycl)