Use <cmath> instead of <math.h> in vanGenuchten-sycl
C-style <math.h> does not reliably place math functions in the global
namespace in all C++ SYCL compilers, causing:

  error: use of undeclared identifier 'ceil'
  error: use of undeclared identifier 'pow'