Compilation fixes for CUDA benchmarks
1. Missing linking with cusparse in simpleSpmv-cuda

```
/usr/bin/ld: kernels.o: in function `spmv_csr(int, int, float const*, unsigned long, float*, float*)':
tmpxft_00212a38_00000000-6_kernels.cudafe1.cpp:(.text+0xa7f): undefined reference to `cusparseCreate'
/usr/bin/ld: tmpxft_00212a38_00000000-6_kernels.cudafe1.cpp:(.text+0xaca): undefined reference to `cusparseCreateCsr'
```

2. Fixing API use in si-cuda

```
si-cuda/src/main.cu(76): error: namespace "thrust" has no member "host"
          thrust::exclusive_scan(thrust::host, d->sizes, d->sizes + d->cardinality, d->offsets, 0);
                                         ^

si-cuda/src/main.cu(76): error: no instance of overloaded function "thrust::exclusive_scan" matches the argument list
            argument types are: (<error-type>, unsigned int *, unsigned int *, unsigned int *, int)
          thrust::exclusive_scan(thrust::host, d->sizes, d->sizes + d->cardinality, d->offsets, 0);
          ^
```